plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-remote-theme
  - jemoji

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Minimal Mistakes specific
title: ERuhl Interactive
name: Ethan Ruhl
url: "https://mademistakes.com"
logo: "/assets/images/logo.png"
search_provider: "google"

permalink: /posts/:categories/:title

include:
  - _pages

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
