plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-remote-theme
  - jemoji

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Minimal Mistakes specific
title: ERuhl Interactive
name: Ethan Ruhl
url: "https://mademistakes.com"
logo: "/assets/images/logo.png"
search_provider: "google"
breadcrumbs: true
read_time: true

permalink: blog/:categories/:title

author:
  name     : "Ethan Ruhl"
  avatar   : "/assets/images/portrait.jpeg"
  bio      : "Game developer and programmer who likes to experiment and make computer go brrrr"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/erinteractive"
    - label: "Mastodon"
      icon: "fab fa-fw fa-link"
      url: "https://mastodon.gamedev.place/@erinteractive"

include:
  - _pages

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
   # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      show_date: true
      read_time: true
      share: true
      related: true
      author_profile: true