plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-remote-theme
  - jemoji

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Minimal Mistakes specific
title: ERuhl Interactive
name: Ethan Ruhl
url: "https://eruhl-interactive.com"
logo: "/assets/images/logo.png"
permalink: blog/:categories/:title

author:
  name     : "Ethan Ruhl"
  avatar   : "/assets/images/portrait.jpeg"
  bio      : "Game developer and programmer who likes to experiment and make computer go brrrr"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/erinteractive"
    - label: "Mastodon"
      icon: "fa-brands fa-mastodon"
      url: "https://mastodon.gamedev.place/@erinteractive"

twitter:
  username: "erinteractive"

og_image: /assets/images/logo.png

social:
  type:  Person
  name:  Ethan Ruhl
  links:
    - "https://twitter.com/erinteractive"
    - "https://mastodon.gamedev.place/@erinteractive"
    - "https://www.linkedin.com/in/ethan-ruhl"
    - "https://eruhlinteractive.itch.io/"

footer:
  links:
    - label: "Mastodon"
      icon: "fa-brands fa-mastodon"
      url: "https://mastodon.gamedev.place/@erinteractive"

    - label: "Itch.io"
      icon: "fa-brands fa-itch-io"
      url: "https://eruhlinteractive.itch.io/"

    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/erinteractive"

    - label: "Linkedin"
      icon: "fa-brands fa-linkedin"
      url: "https://linkedin.com/in/ethan-ruhl"

    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/eruhlinteractive"
   


include:
  - _pages

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
   # _posts
  - scope:
      path: ""
      type: posts
    values:
      breadcrumbs: true
      layout: post
      show_date: true
      read_time: true
      share: true
      #related: true
      author_profile: true
      #header:
      #  overlay_color: "#1f242c"